name: interpolations
channels:
  - conda-forge
dependencies:
  - python=3.10
  # notebooks
  - ipython
  - ipykernel
  # package requirements
  - pandas
  - numpy
  - matplotlib
  - plotly
  - pykrige
  # formatting and linting
  - black
  - black-jupyter
  - flake8
  - flake8-rst-docstrings
  # docs
  - sphinx=6.2.1
  - sphinx_rtd_theme=1.2.2
  - docutils=0.17
  - nbsphinx=0.9.2
  - myst-parser=2.0.0
  # testing
  - pytest
  - pytest-cov
  # pip
  - pip
