name: interpolations
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  # notebooks
  - ipython
  - ipykernel
  # package requirements
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - plotly
  - pykrige
  - scikit-learn
  # formatting and linting
  - black
  - black-jupyter
  - flake8
  - flake8-rst-docstrings
  # docs, updated 5 jul 2023
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.2.2 
  - docutils=0.17.1 # bullet point bug
  - nbsphinx=0.9.2
  - myst-parser=1.0.0
  # testing
  - pytest
  - pytest-cov
  # pip
  - pip
