name: interpolations
channels:
  - conda-forge
dependencies:
  - python=3.10
  # notebooks
  - ipython
  - ipykernel
  # package requirements
  - pandas
  - numpy
  - matplotlib
  - plotly
  - pykrige
  # formatting and linting
  - black
  - black-jupyter
  - flake8
  - flake8-rst-docstrings
  # docs
  - sphinx
  - sphinx_rtd_theme
  - docutils=0.17 # bullet point bug
  - nbsphinx
  - myst-parser
  # testing
  - pytest
  - pytest-cov
  # pip
  - pip
