name: gh-pages-safety

on:
    push:
      branches: [gh-pages]
    
    pull_request:
      branches: [gh-pages]


jobs:
    refuse-commits:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Check for modified files
          run: |
            if git diff --name-only HEAD^ HEAD | grep -vE '^(?!(docs|docsrc)/).*'; then
              echo "Error: Cannot modify files in the docs, docsrc folders."
              exit 1
            fi

