name: Versioning

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify versions
        run: |
          # Get the commit hashes for the base and head branches
          BASE_SHA=$(git rev-parse origin/${{ github.base_ref }})
          HEAD_SHA=$(git rev-parse origin/${{ github.head_ref }})

          # Check if there are changes in the specific folder
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA './py3dinterpolations/')

          if [[ -n "$CHANGED_FILES" ]]; then
            echo "There are changes in the py3dinterpolations folder"
            exit 0
          else
            echo "There are no changes in the py3dinterpolations folder"
            exit 1
          fi


